# Generated by Django 2.1.7 on 2019-03-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190314_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='kind',
            field=models.CharField(choices=[('movie', 'Movie'), ('actor', 'Actor')], default='movie', max_length=10),
        ),
    ]
